project:
  type: website
  output-dir: docs
  
website:
    title: "Data Analysis & Information Extraction"
    page-footer: 
      background: light
      left: 2023 Carviagu. Powered with [Quarto](https://quarto.org/) and [GitHub](https://pages.github.com/)
      right: |
        [![](resources/images/logo2.png){fig-alt="CUNEF" width=65px}](https://cunef.edu)
        
    navbar:
      background: light
      logo: resources/images/subject_logo.png
      title: false
      left:
        - href: index.qmd
          text: Home
        - href: units.qmd
          text: Units
  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true